# This workflow builds and versions each package in the monorepo based on the commit history, and publishes the artifacts to NPMJS.com

name: Publish Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubunutu-latest

    steps:
      # need to have access to latest git for lerna
      - name: install latest git
        run: |
          apt-get update
          apt-get install -y git

      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # ensure we get the git history
          ref: main
          token: ${{secrets.GIT_PUBLISH_TOKEN}}

      # add token to origin url so we can push version updates
      - name: git env setup
        run: |
          git config --global user.name "GitHub Action Runner"
          git config --global user.email # TODO use OS account
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git remote set-url origin https://${{secrets.GIT_PUBLISH_TOKEN}}@github.com/lightning-js/ui-components

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
          # token: ${{ secrets.GIT_PUBLISH_TOKEN }} # TODO do we need this?

      # update container FS permissions to allow scripts to build dist files and allow lerna to bootstrap
      # `find` command lists all dirs in src and runs the permission update on them
      - name: set file permissions
        run: |
          find src/ -type d -exec chmod 777 {} +
          chmod -R 777 .git/

      - name: Build packages
        run: npm run build

      - name: Publish artifacts
        run: pnpm run lerna:publish
        env:
          NPM_TOKEN: ${{ secrets.ARTIFACTORY_ID_TOKEN }} # TODO we probably need a npmjs token
